### ISSUE TITLE
Can you provide some instructions for the installation of this tool....?

### ISSUE THREAD

**Issue by imrannibmg** [macarthur-lab/variant-curation-portal#176]
It will be helpful if you could provide some instructions for the installation of this tool....

**Comment by nawatts** [comment]
Hi @imrannibmg,

Yes, we definitely need some deployment documentation.

In the meantime, the [developer documentation](https://github.com/macarthur-lab/variant-curation-portal/blob/master/CONTRIBUTING.md) provides a starting point.

General reference on deploying Django and setting up authentication can be found here:
* https://docs.djangoproject.com/en/2.2/howto/deployment/
* https://docs.djangoproject.com/en/2.2/howto/auth-remote-user/

There are also some examples of Docker deployments in the [docker](https://github.com/macarthur-lab/variant-curation-portal/tree/master/docker) directory.

**Comment by nawatts** [comment]
More complete deployment documentation is now available in [docs/deployment.md](https://github.com/macarthur-lab/variant-curation-portal/blob/master/docs/deployment.md).

**Comment by imrannibmg** [comment]
@nawatts Thank you so much.
