### ISSUE TITLE
MNP flag change name

### ISSUE THREAD

**Issue by msingerb** [macarthur-lab/variant-curation-portal#188]
Can we change the MNP flag so it says "Flag MNV/Frame restoring indel" in both the portal and the downloaded CSV. If it is too large we can take out the indel at the end.

**Comment by nawatts** [comment]
It's labeled "In-phase MNV or frame-restoring indel" in the curation form.

Need to change it in two other places:
- [ ] Downloaded CSV
- [ ] Legend on the assigned variants page
